[versions]
agp = "8.10.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
cardview = "1.0.0"
coreKtx = "1.13.1"
circleimageview = "3.1.0"
camerax = "1.3.3"
firebaseBom = "33.1.2"
# DIUBAH: Menggunakan versi 17.3.0 untuk menghindari masalah cache
mlkitBarcode = "17.3.0"
guava = "33.0.0-android"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
# DIUBAH: Menggunakan camelCase
extJunit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
# DIUBAH: Menggunakan camelCase
espressoCore = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }
# DIUBAH: Menggunakan camelCase
androidxCoreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
circleimageview = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleimageview" }
# DIUBAH: Menggunakan camelCase
androidxCameraCamera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax" }
# DIUBAH: Menggunakan camelCase
androidxCameraLifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax" }
# DIUBAH: Menggunakan camelCase
androidxCameraView = { group = "androidx.camera", name = "camera-view", version.ref = "camerax" }

# --- LIBRARY FIREBASE ---
firebaseBom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebaseAuth = { group = "com.google.firebase", name = "firebase-auth" }
firebaseFirestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebaseDatabase = { group = "com.google.firebase", name = "firebase-database" }

# --- LIBRARY ML KIT BARCODE SCANNING ---
# INI BENAR: Ini adalah 'com.google.mlkit:barcode-scanning'
mlkitBarcodeScanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "mlkitBarcode" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }


[plugins]
# DIUBAH: Menggunakan camelCase
androidApplication = { id = "com.android.application", version.ref = "agp" }
# DIUBAH: Menggunakan camelCase
googleGmsServices = { id = "com.google.gms.google-services", version = "4.4.2" }